### ISSUE TITLE
Versioning of .idea in src

### ISSUE THREAD

**Issue by atournayre** [orisai/coding-standard-php#3]
Some files templates in .idea causes errors when a project analysis runs.

Of course project analysis should not run on dependencies folder but I think IDE related folder should not be versionned as it is a sharing of coding standard and not an IDE configuration sharing.

**Comment by mabar** [comment]
Hey, .idea folder is provided for configuration of IntelliJ project coding style to be compatible with this library, as described [here](https://github.com/orisai/coding-standard-php/blob/v3.x/docs/README.md#phpstorm--intellij-idea)
It is not internal .idea folder used for repository development.

I can't really change the files to be valid PHP files so if you could just exclude the directory, pleaso do so. Otherwise I would have to make the process less convenient and move the files somewhere else.

**Comment by atournayre** [comment]
It's nice to provide templates to help respect standards.
However those templates are not regular php files (to only speak about php) and so, static analysis tools can parse them and generate errors.

As you say, it is possible to make exclusions in static analysis tools.
But what if multiple librairies in our project dependencies provide those kind of files ? It would be a nightmare to exclude all those.

Normally, analysis tools should not parse vendor directory, and it probably happened because my configuration has a mistake.

By the way, I think those files should live in their own repository, but it means extra work, sync between repos and many other things that consume much time only for some extra standards and helpful files.

So, you can close this issue if no more answer is needed!

Thanks for your feedback.

**Comment by mabar** [comment]
@atournayre Would it help to move these fields outside of src folder? So they are not autoloaded by Composer. Static analyser shouldn't care about files which are not part of the source code

**Comment by mabar** [comment]
I moved files outside of src, hopefully it helps.

Btw, which tools reports it to you? I am not aware of any tools which does that.
